# git-helper 配置文件示例

# 你的 GitHub 用户名
# 用于生成 Pull Request URL，通常也是你 Fork 仓库的所有者
default_fork_username: 424635328 # <-- 请将 'your_github_username' 替换为你的实际 GitHub 用户名

# 你要贡献的原始仓库（上游仓库）的地址
# 用于设置 'upstream' 远程仓库以及尝试提取 default_base_repo
# 可以是 SSH 地址 (如 git@github.com:owner/repo.git) 或 HTTPS 地址 (如 https://github.com/owner/repo.git)
default_upstream_url: git@github.com:424635328/Git-Helper.git # <-- 请将 'upstream_owner/upstream_repo.git' 替换为原始仓库的实际地址

# 原始仓库的名称 (格式为 owner/repo)
# 用于生成 Pull Request URL
# 如果 default_upstream_url 的格式符合 github.com[:/]<owner>/<repo>.git，
# 并且 load_config 函数能成功提取，则此项可以不设置。
# 如果无法自动提取或需要手动指定，请在这里填写。
# default_base_repo: upstream_owner/upstream_repo # <-- 可选，如果需要手动指定或自动提取失败

# 原始仓库的默认分支名称
# 通常是 main 或 master，用于同步 Fork 和一些其他默认操作
default_branch_name: main # <-- 请将 'main' 替换为原始仓库的实际主分支名称

# 你可以在这里添加其他自定义的配置项，
# 如果你的 git_helper 脚本中使用了它们的话。
# 例如：
# editor_command: code --wait # 用于指定提交信息的编辑器（如果脚本支持的话，当前版本不支持）
# preferred_protocol: ssh # 或者 https